### PR TITLE
Iss hipcms 497

### PR DESCRIPTION
**Pull request by janis-kra**

### CODE REVIEW

**Review by maltehol — COMMENTED** [review]
I was able to delete the topic as student.
Did we said students are allowed to do it?

**Comment by janis-kra** [comment]
@maltehol The call to `permissionService.isAllowedToEdit` (~line 250 in app.js) was unchanged so this is quite surprising to me. We agreed that students should not be able to delete a topic and that was addressed in #24 (or at least I thought so, maybe the `isAllowedToEdit` function does not work as we assumed?

**Review by maltehol — DISMISSED** [review]
Ok, from code her, it looks fine, The function should do what expected.
I will try again and on doubt I will ask the server side people.

**Comment by janis-kra** [comment]
Which hopefully doesn't mean asking me :D

Do you remember if this worked when we did the initial implementation of this feature?

**Review by maltehol — APPROVED** [review]
Error was on my side ... Merged

**Pull request merged**
